bins: 
  cargo build --bin

bdev binName:
  cargo build --features nrf52832 --target thumbv7em-none-eabihf --bin {{binName}}

brel binName:
  cargo build --release --features nrf52832 --target thumbv7em-none-eabihf --bin {{binName}}

rdev binName:
  cargo run --features nrf52832 --target thumbv7em-none-eabihf --bin {{binName}}

rrel binName:
  cargo run --release --features nrf52832 --target thumbv7em-none-eabihf --bin {{binName}}

adev binName: 
   probe-rs attach --chip nRF52832_xxAA target/thumbv7em-none-eabihf/debug/{{binName}}
